export default {
  SET_USER_STATE: 'SET_USER_STATE',
  SET_ERROR_STATE: 'SET_ERROR_STATE',
  SET_LOAD_STATE: 'SET_LOAD_STATE',
  SET_EVENTS_STATE: 'SET_EVENTS_STATE',
  ADD_EVENTS_STATE: 'ADD_EVENTS_STATE',
  EDIT_EVENTS_STATE: 'EDIT_EVENTS_STATE',
  DELETE_EVENTS_STATE: 'DELETE_EVENTS_STATE',
  SET_EVENT_JOIN_STATE: 'SET_EVENT_JOIN_STATE',
  ADD_EVENT_JOIN_STATE: 'ADD_EVENT_JOIN_STATE',
  DELETE_EVENT_JOIN_STATE: 'DELETE_EVENT_JOIN_STATE'
}
